name:                YMLParser
version:             0.1.0.0
github:              "githubuser/YMLParser"
license:             BSD3
author:              "ottoMuller"
maintainer:          "otto.muller.general@gmail.com"
copyright:           "2022 Lev Sedov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/YMLParser#readme>

dependencies:
- base >= 4.7 && < 5
- xml-conduit
- text
- containers
- xlsx
- bytestring
- lens
#- text-utf8
#- utf8-string
#- encoding

library:
  source-dirs: src

executables:
  YMLParser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - YMLParser

tests:
  YMLParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - YMLParser
